name: encrypt
version: 5.1.2
description: A set of high-level APIs over PointyCastle for two-way cryptography.
repository: https://github.com/pieces-app/encrypt
publish_to: none

executables:
  secure-random:

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  asn1lib: ^1.5.0
  clock: ^1.1.1
  collection: ^1.17.0
  crypto: ^3.0.2
  pointycastle: ^4.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0

false_secrets:
 - /test/*.pem
